### ISSUE TITLE
Upgrade Ansible

### ISSUE THREAD

**Issue by mastermindg** [nishiki/ansible-role-bind#1]
It would be nice to be on Ansible 2.4 and have all those cool new features. The version would need to updated on the Docker image as well.

**Comment by nishiki** [comment]
Hello, 

My ansible role is compatible with ansible 2.4.
Following your comment, i am improving the tests with many ansible versions.

See the first test: https://travis-ci.org/nishiki/ansible-role-bind/builds/291786094

**Comment by mastermindg** [comment]
All you're doing is exporting the ANSIBLE_VERSION variable outside of the docker container. The Ansible version installed in your Docker container is still 2.2.1.0:

```
$run -it -e ANSIBLE_VERSION=2.2.3.0 nishiki/ansible:stretch ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
It looks like the correct way to set Ansible versions would be to use to customize the provisioner:

```
provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  ansible_version: latest
```

**Comment by mastermindg** [comment]
Looks like stretch isn't supported for an ansible install: https://github.com/neillturner/kitchen-ansible/issues/257

The other alternative would be tagging different versions of your container with Ansible versions, like: 

```nishiki/ansible:2.2.3.0```

**Comment by nishiki** [comment]
For information, i has updated the docker image yesterday, and the `ANSIBLE_VERSION` is for [`.kitchen.yml`.](https://github.com/nishiki/ansible-role-bind/blob/tests-multi-ansible-version/.kitchen.yml)

In[ travis log](https://travis-ci.org/nishiki/ansible-role-bind/jobs/291786097), i show the ansible version before the serverspec tests, and we can see deprecated warning when i use ansible 2.4 but not i use ansible 2.2.

I don't see a problem, do I miss something ?
