### ISSUE TITLE
how to make the keys generate?

### ISSUE THREAD

**Issue by mikysal78** [nishiki/ansible-role-bind#11]
bind_dnssec:
  test.local: 
    ksk:
      algorithm: 8
      digest: 3
      tag: 63805
      public_key: AwEAAbA3M8p+Cpf4k6mZKK8mb1eSIF8yDWXnpmI+i/Jm6CtIYMSigZ4B bmnN+r/SdpeeaPCP5RRZDO/6U0xs2zwPeLs=
      private_key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        33373964393565343638363964366133663235653931386664343435326362333031323130363362
        [...]
        65616337363634636365386166643133373331336333376430353663303563346236316532336532
        62376530646231346237
    zsk:
      algorithm: 8
      digest: 3
      tag: 11346
      public_key: AwEAAd9SkkrJQl4tOsK3zgtfZwmSJBzxU/NjApDZiKo6AVYVhDun6IIl Q/axOe901o+x/iUVwIs7cOMA5Z/h/8G8bq8=
      private_key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        37323036613735396364323363323464393731626466616262613033656264343765306238353934
        [...]
        38653039306430393564346636323966373265343032623430353765646639366536663566653836
        32643931393165643236

**Comment by nishiki** [comment]
Hello @mikysal78,

I haven't made playbook to generate keys yet.
You can generate keys with this commands:

```
dnssec-keygen -a RSASHA256 -b 2048 -r /dev/urandom -n ZONE <domain_name>
dnssec-keygen -f KSK -a RSASHA256 -b 4096 -r /dev/urandom -n ZONE <domain_name>
```

**Comment by mikysal78** [comment]
```
TASK [bind : copy private key] ************************************************************************************************************************************************************************************
fatal: [dns.nnxx]: FAILED! => {"msg": "Attempting to decrypt but no vault secrets found"}
```

My default/main.yml
`bind_dnssec:
  ninux.nnxx:
    ksk:
      algorithm: 8
      digest: 3
      tag: 63805
      public_key: AwEAAbzIMfSp8/m726oWpZRu2411DuD+oJfWCYeTWL6YMnpcHYJp5CB+ MuxD+fE/wLZUAA1xFG+REykM1eavBr41IF+NOiePvXPgda5seAiJ3DNh ar7sXbE/LVyvqPZmOToFbiPARdhOmSV73d1IXJt5U74oBQIUjYa3dCxk KV6KElOX
      private_key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        vMgx9Knz+bvbqhallG7bjXUO4P6gl9YJh5NYvpgyelwdgmnkIH4y7EP58T/AtlQADXEUb5ETKQzV5q8GvjUgX406J4+9c+B1rmx4CIncM2FqvuxdsT8tXK+o9mY5OgVuI8BF2E6ZJXvd3Uhcm3lTvigFAhSNhrd0LGQpXooSU5c=
    zsk:
      algorithm: 8
      digest: 3
      tag: 11346
      public_key: AwEAAdOadUTLwOoNEY4tSsIL1KtwOT+qfbOCYQ5qVed7CmhFVMzIHSVi YSCzAS5eTOFnB46Fd/GxQLuZbvaKC3vWrqKAbgebGPnUtnSprXS/K/py pS0vFrLyIQTp9JygnfvZtUXYGsxx78RiV1s0wxK6Br+Ur+nojzzttn33 82KSMK+7
      private_key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        05p1RMvA6g0Rji1KwgvUq3A5P6p9s4JhDmpV53sKaEVUzMgdJWJhILMBLl5M4WcHjoV38bFAu5lu9ooLe9auooBuB5sY+dS2dKmtdL8r+nKlLS8WsvIhBOn0nKCd+9m1RdgazHHvxGJXWzTDEroGv5Sv6eiPPO22fffzYpIwr7s=
`

**Comment by nishiki** [comment]
use must use `--ask-vault-pass` or `--vault-password-file` with `ansible-playbook` command if use vault encryption
