### ISSUE TITLE
Add support for CAA records

### ISSUE THREAD

**Issue by nomorebugs** [nishiki/ansible-role-bind#2]
CAA records limit valid ssl CA's for Domain:
https://tools.ietf.org/html/rfc6844

They do not have the IN Keyword and a little different structure.

Solution would be to include this special type in db.j2 or to make a _raw_-entry possible to add custom lines to zone file.

If appreciated, I can make a pull request.

**Comment by nishiki** [comment]
it's done, view the commit https://github.com/nishiki/ansible-role-bind/commit/3cdd9cb10c2e6bc34f560ca85ddedddc7bdf2b99 ;)
