### ISSUE TITLE
Add support for new bind>=9.9 inline-signing

### ISSUE THREAD

**Issue by nomorebugs** [nishiki/ansible-role-bind#4]
- dnssec can be handled more comfortable in new transparent handeling of signed zones(no more signature expiration): https://kb.isc.org/article/AA-00626/0/Inline-Signing-in-ISC-BIND-9.9.0-Examples.html

- a check for installed bind version would be needed and if new version dnssec should get enabled the new way

**Comment by nishiki** [comment]
Now with the commit https://github.com/nishiki/ansible-role-bind/commit/19d80e9aef5486f294b3b0b45540e3fbaabb4bd1, you can add any option in zone file
