### ISSUE TITLE
Feature proposal "remove/disable zones"

### ISSUE THREAD

**Issue by nomorebugs** [nishiki/ansible-role-bind#5]
Implement another parameter for zones:
- state: present
- state: disabled (not in named.conf.local)
- state: absent (everything purged)

Currently this role is not able to remove zones, which is a serious limitation. If this feature is not appreciated, I will need to write another role for this purpose.

Furthermore I want to thank @nishiki a lot for implementing all previous Issues almost over night :)

**Comment by nishiki** [comment]
Hello, it done with the commit https://github.com/nishiki/ansible-role-bind/commit/3716a1ac8aca14232f7f1871ad870c9e0af6746d
