### ISSUE TITLE
Feature request: Limit Roll-Out to defined/altered Zones

### ISSUE THREAD

**Issue by nomorebugs** [nishiki/ansible-role-bind#7]
Szenario:
- There are several hundreds of zones defined
- A record is altered at one zone

Current State:
- All zones are rolled-out
- Deployment takes very long

Proposal:
- limit roll-out to a subset of zones:
  - named.confs still contain all zones
  - key-generation, signing, template copy, etc. tasks are skiped
- zones to roll-out are defined via `--extra-vars '{"zone_subset": ["some.zone.fr","other.zone.org"]}'`

**Comment by nomorebugs** [comment]
This isn't something difficult and valuable to the project. I try to avoid forking it by any means. :)
As always I offer to create a pull request.

**Comment by nishiki** [comment]
hello, it done with the commit https://github.com/nishiki/ansible-role-bind/compare/91bb793d8f92...203a6bc5b216
