### ISSUE TITLE
Missing support for SRV Records

### ISSUE THREAD

**Issue by nomorebugs** [nishiki/ansible-role-bind#8]
SRV records are used for service discovery. They are quite common for SIP applications.

Their syntax is: 
srvce.prot.owner-name  ttl  class   rr  pri  weight port target
_http._tcp.example.com.       IN    SRV 0    5      80   www.example.com.

A workaround would be to put everything after SRV into the value attribute:
Should be:
```yaml
{ name: "_http._tcp.example.com.", ttl: 1D, type: SRV, priority: 0, weight: 5, port: 80 target:"www.example.com." }
```
Workaround:
```yaml
{ name: "_http._tcp.example.com.", ttl: 1D, type: SRV, value:"0    5      80   www.example.com." }
```

**Comment by nishiki** [comment]
Hello, it done with the commit https://github.com/nishiki/ansible-role-bind/commit/56ade0a702498f72dd0311f17f938b609fbc5b21
