### ISSUE TITLE
How to do reverse DNS?

### ISSUE THREAD

**Issue by BenjamenMeyer** [nishiki/ansible-role-bind#9]
Reverse DNS is a slightly different db than regular DNS entries in the BInd DB files. How can I get this ansible role to generate them?

Reverse DNS zones named in reverse IP format like: `60.168.192.in-addr.arpa`
And the file looks like:
```
$ORIGIN 60.168.192.in-addr.arpa
$TTL 2d
@  1D IN SOA ns.mydomain.tld   root.mydomain.tld (
2018060600   ; serial
10800        ; refresh
3600         ; retry
604800       ; expiry
86400        ; minimum
);
@  IN  NS ns.mydomain.tld.
1  IN PTR boa.mydomain.tld.
2  IN PTR python.mydomain.tld.
3  IN PTR cobra.mydomain.tld.         
```

NOTE: It'd be really cool if it was automatic based on the regular DNS entries, but I know that's not likely given the format.

**Comment by BenjamenMeyer** [comment]
I'm pretty new to ansible...I may try my hand at a PR to do it, but not sure how successful I'll be.

**Comment by BenjamenMeyer** [comment]
@nishiki I'll give that a try - as I said, I'm relatively new to ansible. Using my home network setup to learn it.

**Comment by BenjamenMeyer** [comment]
Cool...yeah, that solved it. I'll close my PR too

**Comment by nishiki** [comment]
perfect, if you have an other problem with my role, you don't hesitate to open a new issue ;)
